version: "3.8"
services:
  server:
    image: "node:12-alpine"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PLAID_CLIENT_ID=client_id
      - PLAID_CLIENT_SECRET=client_secret
      - PLAID_ENVIRONMENT=development
    command: >
      sh -c "cd app && npm install -g typescript && tsc && node out/app.js"
    volumes:
      - type: bind
        source: ./
        target: /app
  web:
    image: "node:12-alpine"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - type: bind
        source: ./
        target: /app
    command: >
      sh -c "cd app/client && npm start"
